//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.3.0.0 (NJsonSchema v10.1.11.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/// <summary>
/// 
/// </summary>
namespace CryslData
{
    using Newtonsoft.Json;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel.DataAnnotations;
    using System = global::System;


    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("NJsonSchema", "10.1.11.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class SectionSpec
    {
        [JsonProperty("crysl_section", Required = Required.Always)]
        [Required]
        public string Crysl_Section { get; set; }

        [JsonProperty("class_name", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        public string Class_Name { get; set; }


    }

    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("NJsonSchema", "10.1.11.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class SectionObject
    {
        [JsonProperty("crysl_section", Required = Required.Always)]
        [Required]
        public string Crysl_Section { get; set; }

        [JsonProperty("objects_declaration", Required = Newtonsoft.Json.Required.Always)]
        [Required]
        public ICollection<ObjectsDeclaration> Objects_Declaration { get; set; } = new Collection<ObjectsDeclaration>();


    }

    /// <summary>
    /// 
    /// </summary>
    public partial class SectionEnsures
    {
        public string Crysl_Section { get; set; }

        public ICollection<EnsuresObject> EnsuresObject { get; set; } = new Collection<EnsuresObject>();
    }  


    /// <summary>
    /// 
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.11.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class SectionEvent
    {
        [JsonProperty("crysl_section", Required = Required.Always)]
        [Required]
        public string Crysl_Section { get; set; }

        [JsonProperty("methods", Required = Required.Always)]
        [Required]
        public ICollection<Methods> Methods { get; set; } = new Collection<Methods>();


    }

    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("NJsonSchema", "10.1.11.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class SectionOrder
    {
        [JsonProperty("crysl_section", Required = Required.Always)]
        [Required]
        public string Crysl_Section { get; set; }

        [JsonProperty("event_order", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public ICollection<EventOrder> Event_Order { get; set; }


    }

    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("NJsonSchema", "10.1.11.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class SectionConstraints
    {
        [JsonProperty("crysl_section", Required = Required.Always)]
        [Required]
        public string Crysl_Section { get; set; }

        [JsonProperty("constraints", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public ICollection<Constraints> Constraints { get; set; }


    }

    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("NJsonSchema", "10.1.11.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class CryslJsonModel
    {
        [JsonProperty("spec_section", Required = Required.Always)]
        public SectionSpec Spec_Section { get; set; }

        [JsonProperty("object_section", Required = Required.Always)]
        public SectionObject Object_Section { get; set; }

        [JsonProperty("event_section", Required = Required.Always)]
        public SectionEvent Event_Section { get; set; }

        [JsonProperty("order_section", Required = Required.Always)]
        public SectionOrder Order_Section { get; set; }

        [JsonProperty("constraints_section", Required = Required.Always)]
        public SectionConstraints Constraints_Section { get; set; }

        public SectionEnsures Constraints_Ensures { get; set; }


    }

    /// <summary>
    /// 
    /// </summary>
    public partial class EnsuresObject
    {
        public string FuncName { get; set; }

        public ICollection<string> EnsuresList { get; set; } = new Collection<string>();

        public ICollection<string> AfterEventsList { get; set; } = new Collection<string>();

    }

    /*/// <summary>
    /// 
    /// </summary>
    public partial class AfterEventsList
    {
        public string EventName { get; set; }
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class EnsuresList
    {
        public string ObjectName { get; set; }
    }
*/
    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("NJsonSchema", "10.1.11.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class ObjectsDeclaration
    {
        [JsonProperty("object_type", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        public string Object_type { get; set; }

        [JsonProperty("var_name", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        public string Var_name { get; set; }

    }

    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("NJsonSchema", "10.1.11.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class Methods
    {
        [JsonProperty("crypto_signature", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public ICollection<CryptoSignature> Crypto_Signature { get; set; }

        [JsonProperty("aggregator", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public Aggregator Aggregator { get; set; }

    }

    /// <summary>
    /// 
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.11.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class EventOrder
    {
        [JsonProperty("aggregates", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        public string Aggregates { get; set; }

        [JsonProperty("regex", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public string Regex { get; set; }


    }

    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("NJsonSchema", "10.1.11.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class Constraints
    {
        [JsonProperty("object_varname", Required = Required.Always)]
        [Required(AllowEmptyStrings = true)]
        public string Object_Varname { get; set; }

        [JsonProperty("constraints_list", Required = Required.Always)]
        [Required]
        public ICollection<string> Constraints_List { get; set; } = new Collection<string>();

        [JsonProperty("additional_constraints", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public AdditionalConstraints Additional_constraints { get; set; }

    }

    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("NJsonSchema", "10.1.11.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class CryptoSignature
    {
        [JsonProperty("event_var_name", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public string Event_Var_Name { get; set; }

        [JsonProperty("method_name", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public string Method_Name { get; set; }

        [JsonProperty("is_property", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public bool Is_property { get; set; }

        public string Object_variable { get; set; }

        [JsonProperty("argument_types", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public ICollection<ArgumentTypes> Argument_types { get; set; }

    }

    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("NJsonSchema", "10.1.11.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class Aggregator
    {
        [JsonProperty("aggregator_name", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public string Aggregator_Name { get; set; }

        [JsonProperty("aggregators", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public ICollection<Aggregators> Aggregators { get; set; }

    }

    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("NJsonSchema", "10.1.11.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class AdditionalConstraints
    {
        [JsonProperty("object_varname_additional_constraint", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Object_Varname_Additional_Constraint { get; set; }

        [JsonProperty("additional_constraints_list", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public ICollection<string> Additional_Constraints_List { get; set; }

    }

    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("NJsonSchema", "10.1.11.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class ArgumentTypes
    {
        [JsonProperty("argument", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public string Argument { get; set; }

    }

    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("NJsonSchema", "10.1.11.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class Aggregators
    {
        [JsonProperty("aggregator_event_varname", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public string Aggregator_Event_Varname { get; set; }

        [JsonProperty("aggregator_regex", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public string Aggregator_Regex { get; set; }

    }

}